### ISSUE TITLE
SnowView 및 무한 스크롤뷰 빈 화면 이슈

### ISSUE THREAD

**Issue by skpark8** [Genesis-Gyu/GLCommonComponent#1]
- SnowView undefined
- 무한 스크롤뷰 빈 화면 상태

**Comment by Genesis-Gyu** [comment]
- [x] snowView -> ParticlePlayView
- [x] 무한스크롤뷰 빈 화면 -> 수정

**Comment by skpark8** [comment]
잘됩니다!
![Simulator Screen Shot - iPhone 14 Pro - 2022-11-25 at 18 49 25](https://user-images.githubusercontent.com/101547827/203952861-4d6c86d2-9035-4dd1-b361-b5e602e24f72.png)
![Simulator Screen Shot - iPhone 14 Pro - 2022-11-25 at 18 49 35](https://user-images.githubusercontent.com/101547827/203952929-d6ee924c-d3a1-4570-984f-de359bc2b3b9.png)
